name: Robot Framework Tests

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00
  workflow_dispatch:  # Enable manual triggering

jobs:
  Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    #Use the actions/cache action to cache the pip packages for faster installation on subsequent runs.
    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('config/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r config/requirements.txt

    #Add a step to delete the test reports from previous runs before generating new ones, to prevent old reports from cluttering the results directory.
    - name: Delete Old Test Reports
      run: rm -rf test-reports/*

    - name: Run Robot Framework Tests
      run: |
        robot --variable HEADLESS:headless --outputdir test-reports tests || true
    
    #Modify the upload-artifact step to upload all output files generated by Robot Framework, not just those in the results directory.
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-reports

    #Use a more descriptive commit message in the actions-gh-pages step to provide more context to the changes being committed.
    - name: Publish Test Report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./test-reports/
        cname: ${{ env.CNAME }}
        commit_message: Update test report for ${{ github.sha }}

    - name: Display Test Report URL
      run: |
        echo "Test report: https://${{ github.actor }}.github.io/gen-ai-robot-test/report.html"

