name: Robot Framework Tests # Name of the Github Action pipeline

on: # Triggers under which the pipeline will be executed
  push: # Trigger the pipeline on Git push events
    branches:
      - master # Only build on the 'master' branch push events
  pull_request: # Trigger the pipeline on pull request events
  schedule: # Trigger the pipeline on a schedule. The following runs once per day at midnight UTC.
    - cron: '0 0 * * *'
  workflow_dispatch: # Manually trigger the pipeline via the github actions UI


jobs: # Define the jobs that this pipeline will execute.
  Tests: # Job name

    runs-on: ubuntu-latest # Executes the job on an Ubuntu environment
    
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps: # Steps to follow in the job
    - uses: actions/checkout@v3 # This step checks out the code of the project

    - &setup-python
      name: Set Up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip packages # Caches pip packages for future builds
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('config/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache Robot Framework
      uses: actions/cache@v2
      id: rf-cache
      with:
        path: ~/.cache/robotframework-${{ matrix.python-version }}
        key: ${{ runner.os }}-rf-${{ matrix.python-version }}
        restore-keys: |
          ${{ runner.os }}-rf-

    - name: Install Dependencies # Installs dependencies required for Robot framework test execution
      run: |
        python -m pip install --upgrade pip
        pip install -r config/requirements.txt
        pip install robotframework==4.0.1

    - name: Delete Old Test Reports # Deletes previous test reports before running new tests
      run: rm -rf test-reports/*

    - name: Run Robot Framework Tests # Runs Robot framework tests with some custom arguments for the tests. It also masks the errors produced by Robot Framework tests.
      run: |
        robot --variable HEADLESS:headless --exclude visual --outputdir test-reports tests || true
    
    - name: Upload Test Results # Uploads the test results artifact to Github Actions
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-reports

    - name: Publish Test Report # Publishes the test report to Github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./test-reports/
        cname: ${{ env.CNAME }}
        commit_message: Update test report for ${{ github.sha }}

    - name: Display Test Report URL # Displays the URL where test reports can be accessed.
      run: |
        echo "Test report: https://${{ github.actor }}.github.io/gen-ai-robot-test/report.html"
