name: Robot Framework Tests

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00

env:
  HEADLESS: headless

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r config/requirements.txt

    - name: Run Robot Framework Tests
      run: |
        robot --outputdir test-reports tests/
        
    - name: Archive Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: results

    - name: Publish Test Report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./test-reports/
        cname: ${{ env.CNAME }}
        commit_message: Update the test report

    - name: Display Test Report URL
      run: |
        echo "Test report: https://${{ github.actor }}.github.io/gen-ai-robot-test/report.html"

